2024-01-12 23:39:18.593393: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-01-12 23:39:18.615751: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-12 23:39:18.615768: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-12 23:39:18.616327: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-01-12 23:39:18.619667: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-01-12 23:39:19.046036: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-01-12 23:39:19.348242: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-01-12 23:39:19.378031: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-01-12 23:39:19.378199: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-01-12 23:39:19.379270: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-01-12 23:39:19.379603: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-01-12 23:39:19.379702: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-01-12 23:39:20.207019: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-01-12 23:39:20.207143: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-01-12 23:39:20.207330: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-01-12 23:39:20.207409: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 4432 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1660 SUPER, pci bus id: 0000:02:00.0, compute capability: 7.5
2024-01-12 23:39:22.221696: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:454] Loaded cuDNN version 8904
2024-01-12 23:39:23.149795: I external/local_xla/xla/service/service.cc:168] XLA service 0x7fb46a936b20 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2024-01-12 23:39:23.149809: I external/local_xla/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA GeForce GTX 1660 SUPER, Compute Capability 7.5
2024-01-12 23:39:23.152608: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1705120763.216383   24408 device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
WARNING: Version mismatch detected: You are trying to connect to a simulator that might be incompatible with this API 
WARNING: Client API version     = 0.9.15 
WARNING: Simulator API version  = 0.9.14 
  0%|          | 0/9678 [00:00<?, ?episode/s]
Started episode 323 of 10000
Finished episode 323 of 10000
len(agent.replay_memory): 20045
Count of epochs trained: 0	Goal: 1

  0%|          | 0/1 [00:00<?, ?epoch/s][A(array([[[108, 109, 120],
        [109, 110, 119],
        [108, 109, 119],
        ...,
        [ 79,  83,  96],
        [ 79,  83,  96],
        [ 79,  83,  96]],

       [[106, 109, 118],
        [108, 110, 119],
        [108, 110, 119],
        ...,
        [ 79,  83,  96],
        [ 79,  83,  96],
        [ 79,  83,  96]],

       [[108, 110, 119],
        [108, 110, 119],
        [109, 112, 120],
        ...,
        [ 81,  85,  98],
        [ 79,  85,  98],
        [ 79,  85,  98]],

       ...,

       [[130, 129, 128],
        [132, 129, 132],
        [131, 130, 132],
        ...,
        [130, 126, 130],
        [131, 127, 130],
        [130, 126, 129]],

       [[129, 127, 127],
        [130, 127, 129],
        [131, 129, 132],
        ...,
        [130, 126, 129],
        [129, 125, 128],
        [128, 124, 126]],

       [[132, 128, 131],
        [132, 129, 131],
        [133, 130, 135],
        ...,
        [130, 126, 130],
        [131, 127, 130],
        [130, 127, 130]]], dtype=uint8), 330, -198.80606040144647, array([[[108, 109, 119],
        [108, 109, 119],
        [109, 110, 119],
        ...,
        [ 79,  85,  98],
        [ 79,  83,  96],
        [ 79,  83,  96]],

       [[108, 110, 119],
        [109, 110, 120],
        [108, 110, 119],
        ...,
        [ 81,  85,  98],
        [ 81,  85,  98],
        [ 79,  85,  98]],

       [[108, 110, 119],
        [108, 110, 119],
        [109, 110, 119],
        ...,
        [ 81,  85,  98],
        [ 81,  86,  99],
        [ 81,  86,  98]],

       ...,

       [[130, 128, 128],
        [132, 128, 132],
        [131, 128, 132],
        ...,
        [131, 127, 130],
        [131, 127, 129],
        [129, 126, 127]],

       [[130, 128, 129],
        [132, 128, 131],
        [131, 129, 132],
        ...,
        [130, 127, 130],
        [131, 127, 130],
        [129, 125, 127]],

       [[131, 128, 130],
        [133, 129, 132],
        [132, 130, 132],
        ...,
        [131, 128, 131],
        [132, 128, 132],
        [131, 127, 130]]], dtype=uint8), False)
  0%|          | 0/1 [00:00<?, ?epoch/s]
  0%|          | 0/9678 [00:05<?, ?episode/s]
Error message: too many values to unpack (expected 5)
Traceback (most recent call last):
  File "/home/nsambhu/github/carla-race/run/2023_12_18_16rl_custom2.py", line 731, in <module>
    agent.train()
  File "/home/nsambhu/github/carla-race/run/2023_12_18_16rl_custom2.py", line 431, in train
    for (current_state, action, reward, new_state, done) in sequence[-1]:
ValueError: too many values to unpack (expected 5)
Error during episode 323
